/**
 * Question model.
 *
 * A Question is generated by the ModelProvider when it encounters
 * an ambiguity it cannot resolve autonomously. Questions are queued
 * in the Specification and surfaced to the user during `yokai refine`.
 *
 * The `priority.score` is the Expected Information Value (EIV):
 * a 0.0–1.0 score that drives the Question Selection Algorithm.
 * The Engine selects highest-EIV questions first, aiming to
 * "ask the minimum necessary to produce a sufficiently reliable spec."
 *
 * `impact` and `blocking` are intentionally separate semantics:
 *   impact=HIGH, blocking=false → important but engine can draft spec without it
 *   impact=HIGH, blocking=true  → spec cannot be drafted at all without an answer
 */

export type QuestionType =
  | "SINGLE_CHOICE"
  | "MULTIPLE_CHOICE"
  | "OPEN_ENDED"
  | "BOOLEAN";

export type QuestionImpact = "LOW" | "MEDIUM" | "HIGH";

export interface QuestionPriority {
  /** Expected Information Value: 0.0 (trivial) → 1.0 (critical). */
  score: number;
  /** Human-readable rationale for the assigned score. */
  reason: string;
}

export interface Question {
  id: string;
  topic: string;
  /** Why Yokai is asking — provides full context to the user. */
  context: string;
  type: QuestionType;
  options?: string[] | undefined;
  /** The agent's best-guess answer, pre-filled for user confirmation. */
  suggested_answer?: string | undefined;
  impact: QuestionImpact;
  /** If true, the Engine will block spec completion until this is answered. */
  blocking: boolean;
  priority: QuestionPriority;
}
